# Generated by Django 5.0.7 on 2024-10-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categrory',
            new_name='Category',
        ),
    ]
